version: "3.9"
services:
  eureka_server:
    build:
      context: ./eureka_server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
      
  gatewayservice:
    build:
      context: ./gatewayservice
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      
  taskservice:
    build:
      context: ./taskservice
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      
  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    ports:
      - 8082:8082