version: "3.9"
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres-container
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    ports:
      - "5432:5432"