server:
  port: 8765
eureka:
  #  instance:
  #    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
  file:
    name: api-gateway.log
    path: /
