FROM openjdk:21
COPY ./build/libs/cart-service-0.0.1-SNAPSHOT.jar /usr/src/cart-service/cart-service-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/cart-service
CMD ["java", "-jar", "cart-service-0.0.1-SNAPSHOT.jar"]