spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: dbrootpass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  application:
    name: Task Service
  main:
    banner-mode: off
  profiles:
    active: dev
server:
  port: 80

logging:
  level:
    root: INFO
  file:
    name: mylog.log
    path: /

idev:
  openapi:
    dev-url: http://localhost
    prod-url: https://idev-api.com

springdoc:
  swagger-ui:
    path: /idev-documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  #    enabled: false
  api-docs:
    path: /idev-api-docs
  #    enabled: false
  packages-to-scan: ru.geekbrains.homework8

app:
  common:
    logging:
      enabled: true
      level: INFO
    performance:
      enabled: true
      level: INFO