FROM openjdk:21
COPY ./build/libs/review-service-0.0.1-SNAPSHOT.jar /usr/src/review-service/review-service-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/review-service
CMD ["java", "-jar", "review-service-0.0.1-SNAPSHOT.jar"]