FROM openjdk:21
COPY ./build/libs/product-service-0.0.1-SNAPSHOT.jar /usr/src/product-service/product-service-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/product-service
CMD ["java", "-jar", "product-service-0.0.1-SNAPSHOT.jar"]