spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springtestdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    generate-ddl: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  application:
    name:Auth Service
  main:
    banner-mode: off
server:
  port: 8080
  servlet:
    context-path: /