server:
  port: 9001
eureka:
  #  instance:
  #    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/dbproduct
    username: root
    password: dbrootpass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

app:
  common:
    logging:
      enabled: true
      level: INFO
    performance:
      enabled: true
      level: INFO

logging:
  level:
    root: INFO
  file:
    name: product-service.log
    path: /

idev:
  openapi:
    dev-url: http://localhost:9001
    prod-url: https://idev-api.com

springdoc:
  swagger-ui:
    path: /product-service/idev-documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  #    enabled: false
  api-docs:
    path: /product-service/idev-api-docs
  #    enabled: false
  packages-to-scan: ru.gb.homework9.productservice